# TantraFuzz Configuration File

# Gemini AI API Configuration
# The API key is loaded from the GEMINI_API_KEY environment variable.
gemini: {}

# Fuzzer Settings
fuzzer:
  # Number of concurrent threads (workers) to use for fuzzing
  concurrency: 20
  # Timeout in seconds for each HTTP request
  timeout: 10
  # Default User-Agent to use for requests
  user_agent: "TantraFuzz/1.0"
